server:
  port: 8084

spring:
  application:
    name: graph-service
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USER:neo4j}
      password: ${NEO4J_PASS:password}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
      group-id: "graph-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.insta.clone.graphservice.dto"
        spring.json.use.type.headers: false

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

# Custom properties for Kafka topics
app:
  kafka:
    topics:
      user-events: "user.events" # Topic for user creation and deletion events

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html