server:
  port: 8087

spring:
  application:
    name: search-service
  # Elasticsearch configuration
  elasticsearch:
    uris: ${ES_URIS:http://localhost:9200}
    # username: ${ES_USER:} # Add if your ES is secured
    # password: ${ES_PASS:} # Add if your ES is secured
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
      group-id: "search-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "abdumalik.prodev.searchservice.dto"
        spring.json.use.type.headers: false

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

# Custom properties for Kafka topics
app:
  kafka:
    topics:
      user-events: "user.events"
      post-events: "post.events"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html