server:
  port: 8083

spring:
  application:
    name: feed-service
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:feed_db}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
      group-id: "feed-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "abdumalik.prodev.feedservice.dto" # Trust our DTO package
        spring.json.use.type.headers: false

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

# Custom properties for Kafka topics
app:
  kafka:
    topics:
      post-events: "post.events"
      update-events: "update.events"
      delete-events: "delete.events"

# Feign client configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html